version: '3.7'

services:

  redis-master:
    container_name: redis-master
    image: "rhiaqey/redis:latest"
    environment:
      - REDIS_PORT_NUMBER=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "$PWD/data/redis-master/tmp:/opt/bitnami/redis/tmp:rw"
      - "$PWD/data/redis-master/logs:/opt/bitnami/redis/logs:rw"
      - "$PWD/data/redis-master/data:/bitnami/redis/data:rw"
    ports:
      - '6379:6379'
    restart: unless-stopped

  redis-sentinel-1:
    container_name: redis-sentinel-1
    image: "rhiaqey/redis-sentinel:latest"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_MASTER_NAME=mymaster
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "$PWD/data/redis-sentinel-1/tmp:/opt/bitnami/redis-sentinel/tmp:rw"
      - "$PWD/data/redis-sentinel-1/logs:/opt/bitnami/redis-sentinel/logs:rw"
      - "$PWD/data/redis-sentinel-1/data:/bitnami/redis-sentinel/data:rw"
    ports:
      - '26379:26379'
    depends_on:
      - redis-master
    links:
      - redis-master
      - redis-slave-1
      #- redis-slave-2
    restart: unless-stopped

  redis-sentinel-2:
    container_name: redis-sentinel-2
    image: "rhiaqey/redis-sentinel:latest"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_MASTER_NAME=mymaster
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "$PWD/data/redis-sentinel-2/tmp:/opt/bitnami/redis-sentinel/tmp:rw"
      - "$PWD/data/redis-sentinel-2/logs:/opt/bitnami/redis-sentinel/logs:rw"
      - "$PWD/data/redis-sentinel-2/data:/bitnami/redis-sentinel/data:rw"
    ports:
      - '26380:26379'
    depends_on:
      - redis-master
    links:
      - redis-master
      - redis-slave-1
      #- redis-slave-2
    restart: unless-stopped

  redis-sentinel-3:
    container_name: redis-sentinel-3
    image: "rhiaqey/redis-sentinel:latest"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_MASTER_NAME=mymaster
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "$PWD/data/redis-sentinel-3/tmp:/opt/bitnami/redis-sentinel/tmp:rw"
      - "$PWD/data/redis-sentinel-3/logs:/opt/bitnami/redis-sentinel/logs:rw"
      - "$PWD/data/redis-sentinel-3/data:/bitnami/redis-sentinel/data:rw"
    ports:
      - '26381:26379'
    depends_on:
      - redis-master
    links:
      - redis-master
      - redis-slave-1
      #- redis-slave-2
    restart: unless-stopped

  redis-slave-1:
    container_name: redis-slave-1
    image: "rhiaqey/redis:latest"
    environment:
      - REDIS_PORT_NUMBER=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "$PWD/data/redis-slave-1/tmp:/opt/bitnami/redis/tmp:rw"
      - "$PWD/data/redis-slave-1/logs:/opt/bitnami/redis/logs:rw"
      - "$PWD/data/redis-slave-1/data:/bitnami/redis/data:rw"
    ports:
      - '6380:6379'
    depends_on:
      - redis-master
    links:
      - redis-master
    restart: unless-stopped

#   redis-slave-2:
#    container_name: redis-slave-2
#    image: "rhiaqey/redis:latest"
#    environment:
#      - REDIS_PORT_NUMBER=${REDIS_PORT}
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_REPLICATION_MODE=slave
#      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
#      - REDIS_MASTER_HOST=redis-master
#      - REDIS_MASTER_PORT_NUMBER=6379
#      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
#    volumes:
#      - "$PWD/data/redis-slave-2/tmp:/opt/bitnami/redis/tmp:rw"
#      - "$PWD/data/redis-slave-2/logs:/opt/bitnami/redis/logs:rw"
#      - "$PWD/data/redis-slave-2/data:/bitnami/redis/data:rw"
#    ports:
#      - '6381:6379'
#    depends_on:
#      - redis-master
#    links:
#      - redis-master
#    restart: unless-stopped
