version: '3.7'

services:
  redis:
    container_name: redis
    image: "rhiaqey/redis:7.2.4"
    environment:
      - REDIS_PORT_NUMBER=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - "$PWD/data/redis:/bitnami/redis/data:rw"
    restart: unless-stopped
  ops:
    container_name: rhiaqey_ops
    image: "rhiaqey/hub:latest"
    command: generate-keys --skip --write /data/hub
    entrypoint: ops
    volumes:
      - "$PWD/data/hub:/data/hub:rw"
    restart: no
  hub:
    container_name: rhiaqey_hub
    image: "rhiaqey/hub:latest"
    environment:
      - ID=${HUB_ID}
      - NAME=${HUB_NAME}
      - NAMESPACE=${HUB_NAMESPACE}
      - PUBLIC_KEY=${HUB_PUBLIC_KEY_PATH}
      - PRIVATE_KEY=${HUB_PRIVATE_KEY_PATH}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PRIVATE_PORT=${HUB_PRIVATE_PORT}
      - PUBLIC_PORT=${HUB_PUBLIC_PORT}
      - RUST_LOG=${LOG}
      - RUST_BACKTRACE=${BACKTRACE}
    depends_on:
      - ops
      - redis
    entrypoint: hub
    volumes:
      - "$PWD/data/hub:/data/hub:rw"
    links:
      - redis
    restart: unless-stopped
  producer_ticker:
    container_name: rhiaqey_producer_ticker_1
    image: "rhiaqey/ticker:latest"
    environment:
      - ID=${PRODUCER_1_ID}
      - NAME=${PRODUCER_1_NAME}
      - NAMESPACE=${PRODUCER_1_NAMESPACE}
      - PRIVATE_KEY=${PRODUCER_1_PRIVATE_KEY_PATH}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PRIVATE_PORT=${PRODUCER_1_PRIVATE_PORT}
      - PUBLIC_PORT=${PRODUCER_1_PUBLIC_PORT}
      - RUST_LOG=${LOG}
      - RUST_BACKTRACE=${BACKTRACE}
    depends_on:
      - hub
    volumes:
      - "$PWD/data/hub:/data/hub:rw"
    links:
      - redis
    restart: unless-stopped
  producer_iss_position:
    container_name: rhiaqey_producer_iss_position_1
    image: "rhiaqey/iss-position:latest"
    environment:
      - ID=${PRODUCER_2_ID}
      - NAME=${PRODUCER_2_NAME}
      - NAMESPACE=${PRODUCER_2_NAMESPACE}
      - PRIVATE_KEY=${PRODUCER_2_PRIVATE_KEY_PATH}
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PRIVATE_PORT=${PRODUCER_2_PRIVATE_PORT}
      - PUBLIC_PORT=${PRODUCER_2_PUBLIC_PORT}
      - RUST_LOG=${LOG}
      - RUST_BACKTRACE=${BACKTRACE}
    depends_on:
      - hub
    volumes:
      - "$PWD/data/hub:/data/hub:rw"
    links:
      - redis
    restart: unless-stopped
  caddy:
    container_name: caddy
    image: "caddy:2.7.6-alpine"
    environment:
      - HUB_ADMIN_SERVICE=hub:${HUB_PRIVATE_PORT}
      - HUB_SERVICE=hub:${HUB_PUBLIC_PORT}
      - HUB_DOMAIN=${HUB_DOMAIN}
      - USER_EMAIL=${USER_EMAIL}
      - USER_IP=${USER_IP}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/data/caddy:/data/caddy
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - hub
    links:
      - hub
    # build:
      # context: .
      # dockerfile: Dockerfile.caddy
    restart: unless-stopped
