######################################################
##################### RECEIVERS ######################
######################################################

receivers:
  prometheus:
    config:
      scrape_configs:
        # Collect own metrics
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: 'hub1'
          scrape_interval: 15s
          static_configs:
            - targets: ['hub1:3001']
        - job_name: 'hub2'
          scrape_interval: 15s
          static_configs:
            - targets: ['hub2:3001']
  hostmetrics:
    root_path: /
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
      processes:
      # process: # a bug in the process scraper causes the collector to throw errors so disabling it for now

######################################################
##################### PROCESSORS #####################
######################################################

processors:
  resourcedetection/system:
    detectors: [ "system" ]
    system:
      hostname_sources: [ "os" ]
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s

######################################################
##################### EXPORTERS ######################
######################################################

exporters:
  logging:
    loglevel: debug
  otlphttp/openobserve:
    endpoint: ${env:PROMETHEUS_OPEN_OBSERVE_ENDPOINT}
    headers:
      Authorization: ${env:PROMETHEUS_OPEN_OBSERVE_AUTH}
      stream-name: ${env:PROMETHEUS_OPEN_OBSERVE_STREAM_NAME}

######################################################
##################### EXTENSIONS #####################
######################################################

extensions:
  zpages: {}
  memory_ballast:
    size_mib: 512

######################################################
###################### SERVICE #######################
######################################################

service:
  extensions: [zpages, memory_ballast]
  pipelines:
    metrics:
      receivers: [prometheus, hostmetrics]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [logging, otlphttp/openobserve]
