######################################################
##################### RECEIVERS ######################
######################################################

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'hubs'
          scrape_interval: 10s
          static_configs:
            - targets: ['${env:HUB_1_ADDRESS}', '${env:HUB_2_ADDRESS}']
        - job_name: 'gateways'
          scrape_interval: 30s
          static_configs:
            - targets: ['${env:GATEWAY_1_ADDRESS}', '${env:GATEWAY_2_ADDRESS}']

######################################################
##################### PROCESSORS #####################
######################################################

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s

######################################################
##################### EXPORTERS ######################
######################################################

exporters:
  otlphttp/openobserve:
    endpoint: ${env:PROMETHEUS_OPEN_OBSERVE_ENDPOINT}
    headers:
      Authorization: ${env:PROMETHEUS_OPEN_OBSERVE_AUTH}
      stream-name: ${env:PROMETHEUS_OPEN_OBSERVE_STREAM_NAME}

######################################################
##################### EXTENSIONS #####################
######################################################

#extensions:
#  zpages: {}
#  memory_ballast:
#    size_mib: 512

######################################################
###################### SERVICE #######################
######################################################

service:
  # extensions: [zpages, memory_ballast]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlphttp/openobserve]
