services:
  open-observe:
    container_name: open-observe
    image: "openobserve/openobserve:v0.10.8-rc5"
    environment:
      - ZO_TELEMETRY=false
      - ZO_USAGE_ORG=rhiaqey
      - ZO_ROOT_USER_EMAIL=${USER_EMAIL}
      - ZO_ROOT_USER_PASSWORD=${USER_PASSWORD}
      # - ZO_USAGE_REPORTING_CREDS=${PROMETHEUS_OPEN_OBSERVE_AUTH}
      - TZ: "Zulu"
    ports:
      - "5080:5080"
