name: PR Merge

on:
  push:
    branches:
      - master

env:
  CI: true
  IMAGE_NAME: rhiaqey/hub
  CARGO_TERM_COLOR: always
  CARGO_TAG_NAME: "GitHub Actions"
  CARGO_TAG_EMAIL: "github-actions@users.noreply.github.com"

permissions:
  contents: write

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Get latest tag'
        id: prev
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
          #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory
      - name: 'Get next minor version'
        id: next
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.prev.outputs.tag }}
      - name: 'Release new version'
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.next.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"